merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path
from listings import views

urlpatterns = [
    # ADMIN URLS
    path('admin/', admin.site.urls),

    # BAND URLS
    path('bands/', views.band_list, name='band_list'),
    path('bands/<int:id>/', views.band_detail, name='band_detail'),
    path('bands/add/', views.band_create, name='band_create'),
    path('bands/<int:id>/update/', views.band_update, name='band_update'),
    path('bands/<int:id>/delete/', views.band_delete, name='band_delete'),

    # MERCH URLS
    path('listings/', views.list_list, name='list_list'),
    path('listings/<int:id>/', views.list_detail, name='list_detail'),
    path('listings/add/', views.list_create, name='list_create'),
    path('listings/<int:id>/update/', views.list_update, name='list_update'),

    # MISC URLS
    path('contact-us/', views.contact_us, name='contact_us'),
    path('thank-you/', views.email_sent, name='email-sent'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

merchex/listings/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


# Create your models here.
class Band(models.Model):

    class Genre(models.TextChoices):
        ROCK = 'R'
        POP = 'P'
        JAZZ = 'JZ'
        HIP_HOP = 'HH'
        R_AND_B = 'RB'
        COUNTRY = 'CTY'
        DANCE = 'D'
        FRENCH = 'FR'
        OTHER = 'OTHER'

    name = models.CharField(max_length=100)
    title = models.CharField(max_length=200, default="N/A")
    genre = models.CharField(choices= Genre.choices ,max_length=100)
    biography = models.CharField(max_length=2000)
    year_formed = models.IntegerField(validators=[
        MinValueValidator(1900), MaxValueValidator(2024)
    ])
    active = models.BooleanField(default=True)
    official_page = models.URLField(blank=True, null=True)

    def __str__(self):
        return f"{self.name}"

class Listing(models.Model):

    class Type(models.TextChoices):

        DISK = "DISK"
        RECORD = "RECORD"
        CLOTHING = "CLOTHING"
        POSTER = "POSTER"
        MISC = "MISC"

    description = models.CharField(max_length=2000)
    sold = models.BooleanField(default=False)
    years = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(2024)], null=True, blank=True)
    type = models.CharField(choices=Type.choices, max_length=100)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms

from .models import Band, Listing


class ContactUs(forms.Form):
    """ Permet de créer un formulaire de contact """

    name = forms.CharField(label='Nom', max_length=100, required=False)
    email = forms.EmailField(label='Email')
    message = forms.CharField(widget=forms.Textarea, max_length=1000, required=True)

class CreateBand(forms.ModelForm):
    class Meta:
        model = Band
        fields = "__all__"

class CreateListing(forms.ModelForm):
    class Meta:
        model = Listing
        fields = "__all__"

merchex/listings/views.py
from typing import List

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Band, Listing
from .forms import ContactUs, CreateBand, CreateListing
from django.core.mail import send_mail


def band_list(request):
    """Renvoi un template pour afficher la liste des groupes"""
    bands = Band.objects.all()
    return render(request, 'listings/band_list.html', {'bands': bands})

def band_detail(request, id):

    """Renvoi un template pour afficher le detail d'un groupe"""

    band = Band.objects.get(id=id)
    return render(request, 'listings/band_detail.html', {'band': band})

def band_update(request, id):
    """Créer un template de formulaire pour modifier un groupe"""
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        form = CreateBand(request.POST, instance=band)
        if form.is_valid():

            form.save()

            return redirect('band_detail', band.id)

    form = CreateBand(instance=band)
    return render(request, 'listings/band_update.html', {'form': form, 'band': band})

def band_delete(request, id):
    band = Band.objects.get(id=id)
    if request.method == 'POST':
        band.delete()
        return redirect('band_list')

    return render(request, 'listings/band_delete.html', {'band': band})

def list_list(request):
    lists = Listing.objects.all()
    return render(request, 'listings/list_list.html', {'lists': lists})

def list_detail(request, id):
    list = Listing.objects.get(id=id)
    return render(request, 'listings/list_detail.html', {'list': list})

def list_create(request):
    if request.method == 'POST':
        form = CreateListing(request.POST)
        if form.is_valid():
            form.save()
        return redirect('list_list')
    else:
        form = CreateListing()

    return render(request, 'listings/list_create.html', {'form': form})

def list_update(request, id):
    list = Listing.objects.get(id=id)
    if request.method == 'POST':
        form = CreateListing(request.POST, instance=list)
        if form.is_valid():
            form.save()
            return redirect('list_list')
    else:
        form = CreateListing(instance=list)
        return render(request, 'listings/list_update.html', {'form': form})

def contact_us(request):
    if request.method == 'POST':
        form = ContactUs(request.POST)

        if form.is_valid():
            send_mail(
                subject= f"Message from {form.cleaned_data['name'] or 'anonyme'} via Merchex",
                message = form.cleaned_data['message'],
                from_email = form.cleaned_data['email'],
                recipient_list = ['admin@merchex.xyz'],
            )
        return redirect('email-sent')
    else:
        form = ContactUs()
    print('La méthode de requête est : ', request.method)
    print('Les données POST sont : ', request.POST)
    return render(request, 'listings/contact_us.html', {'form': form})

def email_sent(request):
    return render(request, 'listings/email_sent.html')

def band_create(request):
    if request.method == 'POST':
        form =  CreateBand(request.POST)

        if form.is_valid():
            band = form.save()

            return redirect('band_detail', band.id)
    else:
        form = CreateBand()
    return render(request, 'listings/band_add.html', {'form': form})

def about(request):
    return HttpResponse("<h1>About</h1>")

def contact(request):
    return HttpResponse("<h1>Contact</h1> <p>Merci de rester en contact avec nous </p> ")

merchex/listings/templates/listings/band_add.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/band_delete.html
<h1>Supprimer le groupe</h1>

<p>Etes-vous sûr de vouloir supprimer le groupe : {{ band.name }} ?</p>

<form action="" method="post">
{% csrf_token %}
<input type="submit" value="Supprimer">
</form>

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}
 <h1> {{ band.name }}</h1>
<h2>Actif : {{ band.active|yesno }}</h2>
<h2>Album : {{ band.title }}</h2>
<h3>Genre : {{ band.get_genre_display }}</h3>
<p>Biographie : {{ band.year_formed}} ; {{ band.biography }}</p>

<a href="{% url 'band_list' %}">Retour aux groupes</a>
{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Mes groupes et leurs albums</h1>
    <ul>
        {% for band in bands %}
            <li><a href="{% url 'band_detail' band.id %}"> Groupe: {{ band.name|upper }}</a> - <a href="{% url 'band_update' band.id %}">[Modifier]</a> </li>
            <ul>
                <li>
                    Album: {{ band.title }}
                    {% for listing in band.listing_set.all %}
                        <p>Type : {{ listing.type }}</p>
                        <p>Description : {{ listing.description }}</p>
                    {% empty %}
                        <p>Aucun listing pour ce groupe.</p>
                    {% endfor %}
                </li>

            </ul>
        {% endfor %}
    </ul>
<a href="{% url 'band_create' %}">Ajouter un groupe</a>
{% endblock %}

merchex/listings/templates/listings/band_update.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Editer {{ band.name }} </h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>
<a href="{% url 'band_delete' band.id %}">Supprimer le groupe ?</a>
{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}

<html lang="fr">
    <head><title>Merchex</title></head>
    <link rel="stylesheet" href="{% static 'listings/styles.css' %}" />

    <body>
        <nav>
            <a href="{% url 'band_list' %}">Groupes</a>
            <a href="{% url 'band_create' %}">Ajouter un groupe</a>
            <a href="{% url 'list_list' %}">Merch</a>
            <a href="{% url 'list_create' %}">Ajouter du merch</a>
            <a href="{% url 'contact_us' %}">Contactez-nous</a>
        </nav>
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact_us.html
{% extends 'listings/base.html' %}
{% block content %}
    <p>Nous sommes là pour vous aider.</p>

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Envoyer">
    </form>

{% endblock %}

merchex/listings/templates/listings/email_sent.html
{% extends 'listings/base.html' %}

{% block content %}
  <h1>Nous avons bien reçu votre demande</h1>
{% endblock %}

merchex/listings/templates/listings/list_create.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Créer un nouveau groupe</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}

merchex/listings/templates/listings/list_detail.html
{% extends 'listings/base.html' %}

{% block content %}
 <h1> {{ list.name }}</h1>
<h2>Type de merch : {{ list.get_type_display }}</h2>
<h2>Vendu : {{ list.sold|yesno }}</h2>
<h3>Année de parution : {{ list.years }}</h3>
<p>Description : {{ list.description }} </p>

<a href="{% url 'list_list' %}">Retour aux articles</a>
{% endblock %}

merchex/listings/templates/listings/list_list.html
{% extends 'listings/base.html' %}
{% block content %}
<h1>Mes groupes et leurs albums</h1>
    <ul>
        {% for list in lists %}
            <li>Groupe : {{ list.band.name }}</li>
            <ul>
                <li>
                    <p>Année : {{ list.years }}</p>
                    <p>Type de merch : {{ list.get_type_display }}</p>
                </li>
            </ul>
        <h3><a href="{% url 'list_detail' list.id %}">Voir le detail du merch</a> - <a href="{% url 'list_update' list.id %}">[Modifier]</a></h3>
        {% endfor %}
        <h3><a href="{% url 'band_list' %}"> Voir tout les groupes</a></h3>
    </ul>
<a href="{% url 'list_create' %}">Ajouter du merch</a>
{% endblock %}

merchex/listings/templates/listings/list_update.html
{% extends 'listings/base.html' %}

{% block content %}

 <h1>Modifier le merch</h1>

<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Envoyer">
</form>

{% endblock %}